#!/bin/bash
# ReactOS Release Engineering Scripts
# Release_Source - Create the "-src.zip" package

# Sanity checks
if ! source ./Release_Config; then
	echo "Please run Release_Configure first!"
	exit 1
fi

if [ "$ROS_ARCH" = "" ]; then
	echo "Please run this script inside RosBE!"
	exit 1
fi

# Constants
ROOTDIR="$PWD"
WORKDIR="$PWD/Release_WorkDir/Source"
EXPORTDIR="ReactOS-${version}"
SOURCEZIP="ReactOS-${version}-src.zip"

# Start from a clean state
rm -f "${ROOTDIR}/${SOURCEZIP}"
rm -rf "${WORKDIR}"
mkdir -p "${WORKDIR}"
svn export "https://svn.reactos.org/reactos/branches/${branch_name}/reactos" "${WORKDIR}/${EXPORTDIR}" || exit 1
svn export "https://svn.reactos.org/reactos/branches/${branch_name}/rosapps" "${WORKDIR}/${EXPORTDIR}/modules/rosapps" || exit 1
svn export "https://svn.reactos.org/reactos/branches/${branch_name}/wallpapers" "${WORKDIR}/${EXPORTDIR}/modules/wallpapers" || exit 1

# Create the ZIP package
cd "${WORKDIR}"
zip -r "${ROOTDIR}/${SOURCEZIP}" "${EXPORTDIR}"

# We're done!
echo
echo "*******************************************************************************"
echo "Successfully created the following packages:"
echo
echo "   - ${SOURCEZIP}"
echo "*******************************************************************************"
echo
