#!/bin/bash
# ReactOS Release Engineering Scripts
# Release_Source - Create the "-src.zip" package

# Sanity checks
if ! source ./Release_Config; then
	echo "Please run Release_Configure first!"
	exit 1
fi

if [ "$ROS_ARCH" = "" ]; then
	echo "Please run this script inside RosBE!"
	exit 1
fi

# Constants
ROOTDIR="$PWD"
EXPORTDIR="ReactOS-${version}"
SOURCEZIP="ReactOS-${version}-src.zip"

# Start from a clean state
rm -f "${ROOTDIR}/${SOURCEZIP}"

# Create the ZIP package
cd "${REPODIR}"
git archive --format=zip --prefix="${EXPORTDIR}/" -9 --output="${ROOTDIR}/${SOURCEZIP}" "${branch_name}" || exit 1

# We're done!
echo
echo "*******************************************************************************"
echo "Successfully created the following packages:"
echo
echo "   - ${SOURCEZIP}"
echo "*******************************************************************************"
echo
