#!/bin/bash
# Fail immediately if there's any errors in the script
set -euo pipefail

# Constants
ROOTDIR="$PWD"
OPTMODDIR="modules/optional"
OUTPUTDIR="output-MinGW-i386"

echo
echo "*******************************************************************************"
echo "*                            ReactOS Release Script                           *"
echo "*******************************************************************************"
echo

# Ensure we are in RosBE.
if [ "$ROS_ARCH" = "" ]; then
    echo "FAILED: Release script must be run inside RosBE."
    exit 1
fi

# Ensure this is running inside a git directory.
if [ ! -d "${ROOTDIR}/.git" ]; then
    echo "FAILED: Release script must be run inside a ReactOS git directory."
    exit 1
fi

# Check for internet connection.
wget -q --spider https://reactos.org

if [ $? -eq 0 ]; then
    internet=true
else
    echo "Warning: No internet connection detected."
    echo "Optional modules cannot be downloaded and origin cannot be fetched."
    echo
fi

# Get version (ex: 0.4.15-4-ge1e96bf467b5ea).
version=$(git describe)
# Remove git hash at end of the version.
version=${version%-*}
# Change "release" to "rls", if it is in the version name.
version=${version/release/rls}

echo "ReactOS version is ${version}"
echo "ReactOS branch name is $(git rev-parse --abbrev-ref HEAD)"
echo

# Ensure version is not null.
if [ "$version" = "" ]; then
    echo "FAILED: Version is NULL."
    exit 1
fi

# Clean repository, excluding the modules/optional folder and its contents.
git clean -d -f -f -x --exclude="/modules/optional/*"
# Fetch changes from origin if we have an internet connection.
if [ "$internet" ]; then
    git fetch origin
fi
# Reset to the head of the branch
git reset --hard HEAD
echo

# Download the "optional" folder from svn.reactos.org if it isn't already downloaded.
# Ensure the optional modules folder is there and contains the modules we need.
if [ -d "${OPTMODDIR}" ] && [ -f "${OPTMODDIR}/DroidSansFallback.ttf" ] && compgen -G "${OPTMODDIR}/wine_gecko*.msi" > /dev/null; then
    echo "Optional modules already downloaded. Skipping."
    echo "If you have an issue with the optional modules, re-run this script after deleting the directory:"
    echo "    ${ROOTDIR}/${OPTMODDIR}"
elif [ "${internet}" ]; then
    echo "Downloading optional modules..."
    if [ -d "${OPTMODDIR}" ]; then
        rm -rf "${OPTMODDIR}"
    fi
    mkdir "${OPTMODDIR}"
    cd "${OPTMODDIR}"
    wget --recursive --level=1 --no-directories --no-parent --execute robots=off "https://svn.reactos.org/optional"
    # Check that all mandatory files were downloaded.
    if [ ! -f "DroidSansFallback.ttf" ]; then
        echo "DroidSansFallback CJK font missing!"
        exit 1
    fi
    if ! compgen -G "wine_gecko*.msi" > /dev/null; then
        echo "wine_gecko MSI package missing!"
        exit 1
    fi
else
    echo "Missing optional modules and no internet connection. Release aborted."
    exit 1
fi
echo

# BootCD deliverable constants
BOOTCDISO="ReactOS-${version}-${ROS_ARCH}.iso"
BOOTCDZIP="ReactOS-${version}-${ROS_ARCH}.zip"
EXPORTDIR="ReactOS-${version}"
SOURCEZIP="ReactOS-${version}-src.zip"
DELIVERDIR="deliverables"
mkdir -p "${ROOTDIR}/${DELIVERDIR}"

# Build ReactOS
cd "${ROOTDIR}"
./configure.sh -DENABLE_ROSAPPS=1 -DENABLE_WALLPAPERS=1
cd "${OUTPUTDIR}"
ninja bootcd

# Create the ZIP packages for BootCD
echo "Creating BootCD ISO ZIP package..."
mv "bootcd.iso" "${BOOTCDISO}"
zip -9 "${ROOTDIR}/${DELIVERDIR}/${BOOTCDZIP}" "${BOOTCDISO}"

# Create the ZIP package for the source deliverable
echo "Creating source ZIP package..."
cd "${ROOTDIR}"
git archive --format=zip --prefix="${EXPORTDIR}/" -9 --output="${ROOTDIR}/${DELIVERDIR}/${SOURCEZIP}" "$(git rev-parse HEAD)"

# We're done!
echo
echo "*******************************************************************************"
echo "Successfully created the following packages:"
echo "    ${ROOTDIR}/${DELIVERDIR}/${BOOTCDZIP}"
echo "    ${ROOTDIR}/${DELIVERDIR}/${SOURCEZIP}"
echo "*******************************************************************************"
echo
