name: Docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rosbe-unix-release-engineering
        dockerfile: Docker/Dockerfile
        registry: ghcr.io
        addLatest: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
